Throw UserError when an event update reuses an attendance code
acmucsd/membership-portal pull request #148
Opened 2021-01-10 04:05 UTC by sumeet-bansal

There was a QueryFailedError because an event attempted to reuse an existing attendance code. The event creation endpoint has an attendance code check, but the event update endpoint doesn't, so this PR adds that check to the event update endpoint.

2021-01-10 20:56 UTC, shravanhariharan2 requested changes
https://github.com/acmucsd/membership-portal-ui/blob/master/src/containers/admin/EditEventForm.tsx#L83

When editing events, UI passes in all event fields to our API, and not just changes, meaning `changes.attendanceCode` is always present. So if the attendance code doesn't change on edit, then this would throw the user error because the attendance code already exists for an event (namely, this current one).

IMO UI should change their request payload to only send the fields changed, since that's how our API works functionally, but it isn't really clear anywhere in our specification. But since this change would throw an error on every event update that doesn't change its attendance code, maybe we should have `isUnusedAttendanceCode` count the events that aren't the current one?

2021-01-10 21:32 UTC, sumeet-bansal commented
I'll take out all the unchanged fields in `changes` then.

2021-01-13 07:10 UTC, sumeet-bansal commented
@shravanhariharan2 Updated the condition to make sure the attendance code changed from the current one before checking that the new code's unique.

2021-01-14 18:53 UTC, shravanhariharan2 approved these changes

2021-01-14 19:19 UTC, merged