Implemented the ACM Stock Market
acmucsd/membership-portal pull request #303
Opened 2022-04-01 22:26 UTC by shravanhariharan2

Implemented the ACM Stock Market, a new way for members to earn credits. Invest in HACK today! Implemented based on the design doc specs [here](https://www.notion.so/acmucsd/ACM-Stock-Market-Design-Document-49a5a08de3224416a16814cf4c7df6d6)

2022-04-01 22:29 UTC, michl1001 commented
_The start of ACMCoin_

2022-04-01 22:32 UTC, StormFireFox1 commented on types/Enums.ts
> +  ROBINHOOD_MARKETS = 'ROBINHOOD_ARKETS',
nit: enum has typos
```suggestion
  ROBINHOOD_MARKETS = 'ROBINHOOD_MARKETS',
```

2022-04-01 22:33 UTC, StormFireFox1 requested changes
Great work!

So I looked over it, and it works quite well, but I do think we should keep this PR and write some more tests; figure we want to keep the coverage up.

One big issue is I tried investing in HACK, but it says that I don't have enough clout to invest; I thought that was weird, because we both know Dev Team is hella lit.

2022-04-01 23:13 UTC, nishantbalaji commented
ACM TO THE MOON

2022-04-01 23:24 UTC, nishantbalaji approved these changes
lgtm 🚀 🚀 🌕

2022-04-02 00:25 UTC, UdayKalra commented
Nit: among us

2022-04-02 05:40 UTC, sumeet-bansal approved these changes
lgtm, quick nit

2022-04-02 05:40 UTC, sumeet-bansal commented on api/controllers/StockMarketController.ts
> +export class StockMarketController {
```suggestion
export class StonksMarketController {
```

2022-04-02 05:42 UTC, sumeet-bansal commented on api/controllers/StockMarketController.ts
> +  async updateStockPrice(@Body() body: CreateStockRequest, @AuthenticatedUser() user: UserModel) {
wait what lmao

2022-04-02 05:43 UTC, sumeet-bansal commented on api/controllers/StockMarketController.ts
> +  async updateStockPrice(@Body() body: CreateStockRequest, @AuthenticatedUser() user: UserModel) {
centrally planned capitalism 🚀

2022-04-10 00:33 UTC, shravanhariharan2 commented
Stakeholders are interested in a more sophisticated stock market pricing algorithm. ACM Stock Market will return...

2022-04-10 00:33 UTC, closed without merging