Seed data for Resumes
acmucsd/membership-portal pull request #367
Opened 2023-10-13 02:46 UTC by nik-dange

Added seeding data for two users with a visible resume and a hidden resume

2023-10-13 02:47 UTC, nik-dange commented
I printed out the UUID of the user with the visible resume and verified it by fetching all visible resumes. Is there any other testing necessary?

<img width="1051" alt="Screenshot 2023-10-12 at 7 45 16 PM" src="https://github.com/acmucsd/membership-portal/assets/16010723/8986a5d6-1bf7-483f-b8eb-020ddd088934">


<img width="675" alt="Screenshot 2023-10-12 at 7 45 06 PM" src="https://github.com/acmucsd/membership-portal/assets/16010723/d91c18fb-93db-418d-9c8c-ddc7c2e5d480">

2023-10-14 19:18 UTC, dowhep requested changes

2023-10-14 19:18 UTC, dowhep commented on tests/data/index.ts
> +export * from './FileFactory';
Remove unused imports

2023-11-04 20:14 UTC, dowhep approved these changes
LGTM 🚀 best resume pdf imo

2023-11-05 03:12 UTC, merged