Jimmy/sponsorship access type
acmucsd/membership-portal pull request #374
Opened 2023-11-11 20:55 UTC by yimmyj

Closes #370 .

2023-11-13 07:27 UTC, nik-dange requested changes
Just two tiny nits, otherwise LGTM 🚀

2023-11-13 07:27 UTC, nik-dange commented on tests/resume.test.ts
> +  test('sponsorship members can get all visible resumes', async () => {
nit: change to sponsorship managers

2023-11-13 07:27 UTC, nik-dange commented on tests/resume.test.ts
> +    const admin = UserFactory.fake({ accessType: UserAccessType.SPONSORSHIP_MANAGER });
nit: rename admin to something like `sponsorshipManager` for readability

2023-11-22 01:01 UTC, nik-dange commented
Also, make sure to add a seeding user with this role for the testing db

2023-11-29 02:03 UTC, dowhep commented
Remind to rename this PR as well

2023-12-25 23:14 UTC, yimmyj commented
Logged in with newly created sponsorship manager role
<img width="863" alt="Screenshot 2023-12-25 at 3 12 44 PM" src="https://github.com/acmucsd/membership-portal/assets/69327109/0c50617e-f927-4211-a5c5-a8e618c161a9">

Retrieved resumes without error
<img width="887" alt="Screenshot 2023-12-25 at 3 13 04 PM" src="https://github.com/acmucsd/membership-portal/assets/69327109/2487e8ed-dc79-4384-b746-0536fc0e2092">

2023-12-27 07:36 UTC, nik-dange approved these changes
LGTM 🏋️

2024-01-03 17:46 UTC, merged