Add return type for CancelMerchOrder
acmucsd/membership-portal pull request #404
Opened 2024-02-17 21:37 UTC by maxwn04

# Info

Closes **#288**. (If there is no issue for this pull request yet, please create one or
delete this line if the pull request is for a very minor tweak).

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

Adds missing return type

## Changes

- Adds a api response type for cancel merch order

# Type of Change

- [X] Patch (non-breaking change/bugfix)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (A change to a README/description)
- [ ] Continuous Integration/DevOps Change (Related to deployment steps, continuous integration
      workflows, linting, etc.)
- [ ] Other: (Fill In) 

If you've selected Patch, Minor, or Major as your change type, **make sure to bump the version before merging in `package.json`!**
# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally.
- [ ] on the testing API/testing database.
- [ ] with appropriate Postman routes. Screenshots are included below.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [ ] I have appropriately edited the API version in the `package.json` file.
- [x] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Postman testing passing successfully.

2024-02-27 01:16 UTC, maxwn04 commented
![image](https://github.com/acmucsd/membership-portal/assets/73797155/9fa13514-99b3-4283-8359-6bb22907a26e)
Cancel Merch Order Postman

2024-03-07 01:25 UTC, nik-dange requested changes
one nit but lgtm

2024-03-07 01:25 UTC, nik-dange commented on types/ApiResponses.ts
> +export interface CancelMerchOrderResponse extends ApiResponse {
Can this (and possibly any other Merch Store related return types be moved to the correct part of this file?

2024-03-07 01:27 UTC, nik-dange commented
Also make sure to bump package.json version

2024-03-07 01:28 UTC, nik-dange commented on types/ApiResponses.ts
> +export interface CancelMerchOrderResponse extends ApiResponse {
Feel free to clean this file up if you want it feels very messy at the bottom

2024-03-13 00:00 UTC, dowhep approved these changes
Great Catch with the missing return type information!

LGTM 🚀 🚀 

As Nikhil noted, make sure to bump package.json version before merging

2024-03-30 03:29 UTC, nik-dange approved these changes

2024-03-30 03:29 UTC, merged