Add names to retroactive attendance form
acmucsd/membership-portal pull request #407
Opened 2024-02-25 06:50 UTC by ryanDing26

# Info

Closes **#322**. 

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

Faris wanted to change the functionality on the retroactive attendance form (within the admin dashboard) so that it displayed names in the format `firstName lastName (email)` so that it would be easier to autocomplete manual attendance by name instead of asking people for their email for points.

## Changes

- Changed the emailRaw variable in `getAllEmails` in UserRepository.ts such that it built a query with the firstName and lastName of a user from the UserModel object alongside the existing email selection
- Changed the return statement of `getAllEmails` in UserRepository.ts such that instead of just mapping all the emails, it would map `firstName lastName (email)`

# Type of Change

- [ ] Patch (non-breaking change/bugfix)
- [x] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (A change to a README/description)
- [ ] Continuous Integration/DevOps Change (Related to deployment steps, continuous integration
      workflows, linting, etc.)
- [ ] Other: (Fill In) 

If you've selected Patch, Minor, or Major as your change type, **make sure to bump the version before merging in `package.json`!**
# Testing

I have tested that my changes fully resolve the linked issue ...

- [ ] locally.
- [ ] on the testing API/testing database.
- [ ] with appropriate Postman routes. Screenshots are included below.

# Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have followed the style guidelines of this project.
- [ ] I have appropriately edited the API version in the `package.json` file.
- [x] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Postman testing passing successfully.

2024-02-29 07:13 UTC, nik-dange requested changes
Just a small nit. You'll need to fix your tests and run the linter before being able to merge though, make sure those pass before opening a PR

2024-02-29 07:13 UTC, nik-dange commented on repositories/UserRepository.ts
>      const emailsRaw = await this.repository
can we change this variable name to `emailsNamesRaw` so it's a bit more descriptive?

2024-03-02 01:28 UTC, dowhep commented
Nit: Since you will be returning an array of strings that concatenate names and emails, it would be cleaner and more correct to define a new type for such strings. Maybe make the field name "namesAndEmails" or something.

2024-03-28 04:49 UTC, nik-dange approved these changes
lgtm. **please bump package version before merging**

2024-04-02 09:36 UTC, ryanDing26 commented
This is the final version I would like to submit for the PR. Let me know if any more changes need to be made!

2024-04-17 22:44 UTC, nik-dange requested changes
One quick question

2024-04-17 22:44 UTC, nik-dange commented on types/ApiResponses.ts
> +}
I think this type might be better under `types/internal`, thoughts?

2024-04-17 22:44 UTC, nik-dange commented on services/UserAccountService.ts
> +  public async getAllNamesEmails() {
nit: rename to getAllNamesAndEmails

2024-04-17 22:44 UTC, nik-dange commented on repositories/UserRepository.ts
> +  public async getAllNamesEmails(): Promise<NameEmail[]> {
nit: rename to getAllNamesAndEmails

2024-04-17 23:04 UTC, nik-dange commented on types/ApiResponses.ts
> +}
nvm, seems fine

2024-04-17 23:06 UTC, nik-dange commented on types/ApiResponses.ts
> +export interface NameEmail {
nit: rename to NameAndEmail

2024-04-25 00:03 UTC, echang594 commented on services/UserAccountService.ts
> +  public async getAllNamesAndEmails() {
Can you add the return type back

2024-04-25 00:13 UTC, echang594 submitted a review, later dismissed
See my other comment

2024-04-30 02:29 UTC, nik-dange approved these changes
@ryanDing26 looks good to me, just threw in a return type and did some listing

2024-04-30 02:31 UTC, merged