Bug/restrict event deletion
acmucsd/membership-portal pull request #410
Opened 2024-02-27 09:20 UTC by echang594

# Info

Closes **#199**. (If there is no issue for this pull request yet, please create one or
delete this line if the pull request is for a very minor tweak).

# Description

What changes did you make? List all distinct problems that this PR addresses. Explain any relevant
motivation or context.

[description]

## Changes

- [Fill in here]

# Type of Change

- [ ] Patch (non-breaking change/bugfix)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (A change to a README/description)
- [ ] Continuous Integration/DevOps Change (Related to deployment steps, continuous integration
      workflows, linting, etc.)
- [ ] Other: (Fill In) 

If you've selected Patch, Minor, or Major as your change type, **make sure to bump the version before merging in `package.json`!**
# Testing

I have tested that my changes fully resolve the linked issue ...

- [ ] locally.
- [ ] on the testing API/testing database.
- [ ] with appropriate Postman routes. Screenshots are included below.

# Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have followed the style guidelines of this project.
- [ ] I have appropriately edited the API version in the `package.json` file.
- [ ] My changes produce no new warnings.

# Screenshots

Please include a screenshot of your Postman testing passing successfully.

2024-02-29 00:27 UTC, maxwn04 approved these changes
🚀 LGTM 🚀

2024-02-29 21:10 UTC, nik-dange requested changes
Just left one comment to add a test case, other than that LGTM. Great work on your first feature, and awesome job on making the admin tests more concise! localeCompare to the rescue 😁

2024-02-29 21:11 UTC, nik-dange commented on tests/event.test.ts
> +  });
Also, bump the patch number in package.json for this bug fix

2024-02-29 21:28 UTC, echang594 commented on tests/event.test.ts
> +  });
Alright

2024-03-01 02:01 UTC, nik-dange approved these changes
LGTM 🚀

2024-03-01 04:47 UTC, merged